"""HeadRush Core driver — read-only phase.

See ``docs/headrush_core.md`` for the design this implements, the object map of
the device's local API, and the open questions that gate the write path.

Nothing here can modify the instrument: :mod:`client` exposes no PUT, and its
object-method call is restricted to a hard-coded allow-list of pure reads.
"""

from __future__ import annotations

from fretwise.devices.headrush_core.catalog import (
    CATALOG_SCHEMA_VERSION,
    BlockSchema,
    Catalog,
    ParamSchema,
    build_catalog,
    catalog_path,
    parse_blocks,
    write_catalog,
)
from fretwise.devices.headrush_core.chain import (
    CC_BYPASS_BASE,
    FREE_SLOTS,
    FROZEN_HEAD,
    HARD_PRECEDENCE,
    REVERB_SLOT,
    ChainError,
    Placement,
    assign_slots,
    check_relocation,
    describe,
    placement_calls,
    validate_order,
)
from fretwise.devices.headrush_core.client import (
    DEFAULT_HOST,
    HOST_ENV_VAR,
    PURE_METHODS,
    ChainSlot,
    CoreClient,
    CoreWriteClient,
    DeviceError,
    DeviceIdentity,
    DeviceProtocolError,
    DeviceSnapshot,
    DeviceTransport,
    DeviceUnreachableError,
    DeviceWriteTransport,
    RigSummary,
    UnsafeMethodError,
    resolve_host,
)
from fretwise.devices.headrush_core.params import (
    ALGO_NAMES,
    ALGOS_IN_USE,
    ParamError,
    device_value,
    enum_index,
    enum_label,
    format_display,
    fround,
    round_trip_error,
    to_display,
    to_normalized,
    within_grid,
)
from fretwise.devices.headrush_core.plan import (
    BINDING_SCHEMA_VERSION,
    GENERATED_PREFIX,
    Plan,
    PlanError,
    Step,
    build_plan,
    load_binding,
)
from fretwise.devices.headrush_core.pusher import (
    WRITE_ENV_VAR,
    ApplyReport,
    DeviceBusy,
    VerificationFailed,
    WriteRefused,
    apply_plan,
    plan_token,
    summarize_state,
)
from fretwise.devices.headrush_core.snapshot import (
    SNAPSHOT_SCHEMA_VERSION,
    Change,
    RigSnapshot,
    capture_rig,
    default_snapshot_path,
    diff_snapshots,
    load_snapshot,
    write_snapshot,
)

__all__ = [
    "ALGOS_IN_USE",
    "ALGO_NAMES",
    "ApplyReport",
    "BINDING_SCHEMA_VERSION",
    "BlockSchema",
    "CATALOG_SCHEMA_VERSION",
    "CC_BYPASS_BASE",
    "Catalog",
    "ChainError",
    "ChainSlot",
    "Change",
    "CoreClient",
    "CoreWriteClient",
    "DEFAULT_HOST",
    "DeviceBusy",
    "DeviceError",
    "DeviceIdentity",
    "DeviceProtocolError",
    "DeviceSnapshot",
    "DeviceTransport",
    "DeviceUnreachableError",
    "DeviceWriteTransport",
    "FREE_SLOTS",
    "FROZEN_HEAD",
    "GENERATED_PREFIX",
    "HARD_PRECEDENCE",
    "HOST_ENV_VAR",
    "PURE_METHODS",
    "ParamError",
    "ParamSchema",
    "Placement",
    "Plan",
    "PlanError",
    "REVERB_SLOT",
    "RigSnapshot",
    "RigSummary",
    "SNAPSHOT_SCHEMA_VERSION",
    "Step",
    "UnsafeMethodError",
    "VerificationFailed",
    "WRITE_ENV_VAR",
    "WriteRefused",
    "apply_plan",
    "assign_slots",
    "build_catalog",
    "build_plan",
    "capture_rig",
    "catalog_path",
    "check_relocation",
    "default_snapshot_path",
    "describe",
    "device_value",
    "diff_snapshots",
    "enum_index",
    "enum_label",
    "format_display",
    "fround",
    "load_binding",
    "load_snapshot",
    "parse_blocks",
    "placement_calls",
    "plan_token",
    "resolve_host",
    "round_trip_error",
    "summarize_state",
    "to_display",
    "to_normalized",
    "validate_order",
    "within_grid",
    "write_catalog",
    "write_snapshot",
]
