"""Seed FretWise's GP-180 rig bank from the captured preset list.

The GP-180 displays patches as 001..200, while FretWise stores MIDI program
numbers as zero-based values. This script converts the captured full patch names
into `partitions/rigs/rig_bank.json` and records cautious artist/genre guesses.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from fretwise.rig_bank import RigBank, RigBinding, RigProfile, save_rig_bank

SOURCE = "gp180_screenshot_2026-06-17"
MODULE_SOURCE = "gp180_screenshot_2026-07-14"

ModuleRow = tuple[str, str, bool]
CAPTURED_MODULES: dict[int, tuple[ModuleRow, ...]] = {
    0: (
        ("NR", "Gate 3", True),
        ("WAH", "V-Wah", False),
        ("DST", "Green OD", True),
        ("AMP", "Flagman 1", True),
        ("CAB/IR", "Flagman 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    1: (
        ("PRE", "COMP", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    2: (
        ("NR", "Gate 3", True),
        ("AMP", "Tweedy", True),
        ("CAB/IR", "TWD LUX 1x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    3: (
        ("AMP", "Foxy 30N", True),
        ("CAB/IR", "Foxy 2x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    4: (
        ("NR", "Gate 3", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "Foxy 1x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    5: (
        ("NR", "Gate 3", True),
        ("AMP", "UK 900", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    6: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess DualV", True),
        ("CAB/IR", "Mess 4x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    7: (
        ("AMP", "Match CL", True),
        ("CAB/IR", "Bog 2x12", True),
        ("RVB", "Tube Spring", True),
        ("VOL", "Volume", True),
    ),
    8: (
        ("NR", "Gate 3", True),
        ("AMP", "Match OD", True),
        ("CAB/IR", "Foxy 1x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    9: (
        ("NR", "Gate 3", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Mess 4x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    10: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "Dual Echo", True),
        ("RVB", "Church", True),
        ("VOL", "Volume", True),
    ),
    11: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("DST", "B-Boost", True),
        ("AMP", "L-Star CL", True),
        ("CAB/IR", "L-Star 2x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    12: (
        ("NR", "Gate 3", True),
        ("DST", "Scream OD", True),
        ("AMP", "Solo100 LD", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Digital Delay S", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    13: (
        ("NR", "Gate 3", True),
        ("DST", "Yellow OD", True),
        ("AMP", "UK 900", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    14: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("DST", "Super OD", True),
        ("AMP", "UK 50 JP", True),
        ("CAB/IR", "UK Basket 4x12", True),
        ("EQ", "Guitar EQ 2", True),
        ("DLY", "Ping Pong", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    15: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Mess 2C+ 3", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    16: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Z38 OD", True),
        ("CAB/IR", "Bog 2x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    17: (
        ("NR", "Gate 3", True),
        ("PRE", "B-Boost", True),
        ("DST", "Green OD", True),
        ("AMP", "Flagman 1", True),
        ("CAB/IR", "Flagman 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    18: (
        ("NR", "Gate 3", True),
        ("PRE", "T-Wah", True),
        ("DST", "OD 9", True),
        ("AMP", "Eagle 120", True),
        ("CAB/IR", "Bog 4x12", True),
        ("MOD", "O-Phase", False),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    19: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "Bellman 59B", True),
        ("CAB/IR", "TWD LUX 1x12", True),
        ("MOD", "G-Chorus", False),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    20: (
        ("NR", "Gate 3", True),
        ("WAH", "V-Wah", False),
        ("DST", "Red Haze", True),
        ("AMP", "UK 45+", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("MOD", "V-Roto", False),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    21: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "Foxy 1x12", True),
        ("MOD", "Jet", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    22: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Bog RedM", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    23: (
        ("NR", "Gate 3", True),
        ("PRE", "OD 9", True),
        ("DST", "Green OD", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    24: (
        ("PRE", "COMP", True),
        ("MOD", "O-Phase", False),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("EQ", "Guitar EQ 1", False),
        ("DLY", "Pure", False),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    25: (
        ("PRE", "COMP4", True),
        ("AMP", "J-120 CL", True),
        ("CAB/IR", "J-120 2x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    26: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("AMP", "Bellman 59B", True),
        ("CAB/IR", "Twin 2x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    27: (
        ("PRE", "Boost", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    28: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("AMP", "Match OD", True),
        ("CAB/IR", "Foxy 2x12", True),
        ("RVB", "Tube Spring", True),
        ("VOL", "Volume", True),
    ),
    29: (
        ("NR", "Gate 3", True),
        ("PRE", "OD 9", True),
        ("DST", "Tube Clipper", True),
        ("AMP", "UK 50+", True),
        ("CAB/IR", "Bog 2x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    30: (
        ("NR", "Gate 3", True),
        ("DST", "Scream OD", True),
        ("AMP", "Mess 2C+ 3", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "BBD Delay S", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    31: (
        ("NR", "Gate 3", True),
        ("DST", "TaiChi OD", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "Foxy 2x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    32: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "Bog RedM", True),
        ("CAB/IR", "Bog 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    33: (
        ("NR", "Gate 3", True),
        ("DST", "Super OD", True),
        ("AMP", "Solo100 LD", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    34: (
        ("NR", "Gate 3", True),
        ("DST", "Darktale", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Bellman 4x10", True),
        ("MOD", "C-Chorus", True),
        ("VOL", "Volume", True),
    ),
    35: (
        ("NR", "Gate 3", True),
        ("DST", "Boost", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Solo 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    36: (
        ("NR", "Gate 3", True),
        ("DST", "Yellow OD", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    37: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "UK 2x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    38: (
        ("NR", "Gate 3", True),
        ("PRE", "Blues OD", True),
        ("DST", "Darktale", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    39: (
        ("PRE", "COMP4", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("EQ", "Guitar EQ 1", False),
        ("DLY", "Pure", True),
        ("RVB", "Tube Spring", True),
        ("VOL", "Volume", True),
    ),
    40: (
        ("NR", "Gate 3", True),
        ("DST", "Scream OD", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "N-Star", True),
        ("VOL", "Volume", True),
    ),
    41: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", False),
        ("MOD", "C-Chorus", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    42: (
        ("NR", "Gate 3", True),
        ("DST", "Scream OD", False),
        ("AMP", "UK 50JP", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    43: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", False),
        ("AMP", "UK 50+", True),
        ("CAB/IR", "UK Vintage 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    44: (
        ("NR", "Gate 3", True),
        ("DST", "Super OD", True),
        ("AMP", "UK 50+", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    45: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "UK 50+", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    46: (
        ("NR", "Gate 3", True),
        ("WAH", "V-Wah", False),
        ("DST", "Green OD", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "Pure", False),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    47: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("DST", "Green OD", True),
        ("AMP", "Bog RedM", True),
        ("CAB/IR", "UK 2x12", True),
        ("MOD", "Jet", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    48: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", False),
        ("DST", "Green OD", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "LUX 1x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    49: (
        ("NR", "Gate 3", True),
        ("MOD", "O-Phase", True),
        ("PRE", "Boost", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    50: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("DST", "Yellow OD", False),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Mess 4x12", True),
        ("EQ", "Guitar EQ 1", False),
        ("MOD", "Jet", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    51: (
        ("NR", "Gate 3", True),
        ("PRE", "OD 9", False),
        ("DST", "Penesas", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "LUX 1x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    52: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "TWD LUX 1x12", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    53: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    54: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Mess DualM", True),
        ("CAB/IR", "Mess 4x12", True),
        ("EQ", "Guitar EQ 2", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    55: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "Flagman+ 1", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("MOD", "C-Chorus", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    56: (
        ("NR", "Gate 3", True),
        ("DST", "OD 9", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Dizz 4x12", True),
        ("EQ", "Guitar EQ 2", True),
        ("MOD", "Jet", False),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    57: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("DST", "OD 9", True),
        ("AMP", "UK 900", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    58: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("DST", "OD 9", True),
        ("AMP", "Mess 2C+ 3", True),
        ("CAB/IR", "Juice 4x12", True),
        ("EQ", "Mess EQ", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    59: (
        ("NR", "Gate 3", True),
        ("DST", "Darktale", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("MOD", "C-Chorus", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    60: (
        ("NR", "Gate 3", True),
        ("DST", "Green OD", True),
        ("AMP", "Foxy 30TB", True),
        ("CAB/IR", "Foxy 1x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    61: (
        ("NR", "Gate 3", True),
        ("PRE", "OD 9", False),
        ("DST", "Green OD", True),
        ("AMP", "Mess DualM", True),
        ("CAB/IR", "Dizz 4x12", True),
        ("EQ", "Guitar EQ 2", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    62: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess DualM", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    63: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess DualM", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    64: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess DualM", True),
        ("CAB/IR", "Mess 4x12", True),
        ("MOD", "C-Chorus", True),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    65: (
        ("NR", "Gate 3", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    66: (
        ("NR", "Gate 3", True),
        ("AMP", "Flagman 1", True),
        ("CAB/IR", "Flagman 4x12", True),
        ("PRE", "Pitch", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    67: (
        ("NR", "Gate 3", True),
        ("AMP", "Flagman 1", True),
        ("CAB/IR", "Flagman 4x12", True),
        ("PRE", "Pitch", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    68: (
        ("NR", "Gate 3", True),
        ("WAH", "V-Wah", True),
        ("DST", "Green OD", True),
        ("AMP", "Mess2C+ 2", True),
        ("CAB/IR", "Mess 4x12", True),
        ("EQ", "Guitar EQ 1", False),
        ("MOD", "G-Chorus", False),
        ("DLY", "Pure", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    69: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("AMP", "Bog BlueV", True),
        ("CAB/IR", "Bog 2x12", True),
        ("MOD", "Auto Swell", True),
        ("DLY", "Sweet Echo", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    70: (
        ("NR", "Gate 3", True),
        ("PRE", "Step Filter", True),
        ("AMP", "Silver Twin", True),
        ("CAB/IR", "REV 2x12", True),
        ("DLY", "Digital Delay S", True),
        ("RVB", "Sweet Space", True),
        ("VOL", "Volume", True),
    ),
    71: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("DLY", "Pure", True),
        ("RVB", "Church", True),
        ("VOL", "Volume", True),
    ),
    72: (
        ("NR", "Gate 3", True),
        ("PRE", "OCTA", True),
        ("DST", "Tube Clipper", True),
        ("AMP", "Tweedy", True),
        ("CAB/IR", "TWD LUX 1x12", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    73: (
        ("PRE", "Boost", True),
        ("AMP", "J-120 CL", True),
        ("CAB/IR", "J-120 2x12", True),
        ("MOD", "C-Chorus", True),
        ("DLY", "Dual Echo", True),
        ("RVB", "Sweet Space", True),
        ("VOL", "Volume", True),
    ),
    74: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess2C+ 2", True),
        ("CAB/IR", "Mess 4x12", True),
        ("MOD", "Vibe", True),
        ("RVB", "Church", True),
        ("VOL", "Volume", True),
    ),
    75: (
        ("NR", "Gate 3", True),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Mess 4x12", True),
        ("MOD", "Freeze", False),
        ("DLY", "Pure", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    76: (
        ("NR", "Gate 3", True),
        ("AMP", "Mess 2C+ 3", True),
        ("CAB/IR", "Mess 4x12", True),
        ("MOD", "Vibrato", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    77: (
        ("NR", "Gate 3", True),
        ("PRE", "Boost", True),
        ("WAH", "V-Wah", False),
        ("AMP", "Silver Twin", True),
        ("CAB/IR", "LUX 1x12", True),
        ("MOD", "O-Trem", True),
        ("RVB", "N-Star", True),
        ("VOL", "Volume", True),
    ),
    78: (
        ("NR", "Gate 3", True),
        ("DST", "Tube Clipper", True),
        ("AMP", "Mess2C+ 1", True),
        ("PRE", "OCTA", True),
        ("CAB/IR", "Mess 4x12", True),
        ("MOD", "Detune", True),
        ("RVB", "Concert", True),
        ("VOL", "Volume", True),
    ),
    79: (
        ("PRE", "Boost", True),
        ("AMP", "Z38 CL", True),
        ("CAB/IR", "Foxy 2x12", True),
        ("MOD", "C-Chorus", False),
        ("RVB", "Shimmer", True),
        ("VOL", "Volume", True),
    ),
    80: (
        ("NR", "Gate 3", True),
        ("PRE", "S to H", True),
        ("DST", "OD 9", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "BBD Delay S", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    81: (
        ("NR", "Gate 3", True),
        ("PRE", "H to S", True),
        ("DST", "OD 9", True),
        ("AMP", "UK 800", True),
        ("CAB/IR", "UK 30 4x12", True),
        ("DLY", "BBD Delay S", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    82: (
        ("NR", "Gate 3", True),
        ("PRE", "AC Sim", True),
        ("DST", "Boost", True),
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", True),
        ("EQ", "Guitar EQ 2", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    83: (
        ("NR", "Gate 3", True),
        ("PRE", "Hammy", True),
        ("DST", "Green OD", False),
        ("AMP", "EV 51", True),
        ("CAB/IR", "Mess 4x12", True),
        ("DLY", "Dual Echo", False),
        ("RVB", "Church", True),
        ("VOL", "Volume", True),
    ),
    84: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", False),
        ("DST", "Red Haze", True),
        ("AMP", "Silver Twin", True),
        ("CAB/IR", "TWD LUX 1x12", False),
        ("EQ", "Guitar EQ 2", True),
        ("MOD", "O-Phase", False),
        ("RVB", "Room", True),
        ("VOL", "Volume", True),
    ),
    85: (
        ("PRE", "COMP4", True),
        ("WAH", "B-Wah", False),
        ("AMP", "Bellman 59N", True),
        ("CAB/IR", "AMPG 2x12", True),
        ("EQ", "Bass EQ 1", True),
        ("RVB", "Room", False),
        ("VOL", "Volume", True),
    ),
    86: (
        ("PRE", "COMP", True),
        ("WAH", "C-Wah", False),
        ("DST", "Green OD", False),
        ("AMP", "Mini Bass", True),
        ("CAB/IR", "AMPG 4x10", True),
        ("EQ", "Bass EQ 1", True),
        ("VOL", "Volume", True),
    ),
    87: (
        ("PRE", "COMP4", True),
        ("WAH", "V-Wah", False),
        ("AMP", "Classic Bass", True),
        ("CAB/IR", "MATT 2x12", True),
        ("EQ", "Bass EQ 1", True),
        ("VOL", "Volume", True),
    ),
    88: (
        ("PRE", "COMP4", True),
        ("AMP", "Foxy Bass", True),
        ("CAB/IR", "Mess BS 2x10", True),
        ("EQ", "Bass EQ 1", True),
        ("RVB", "Room", True),
        ("VOL", "Volume", True),
    ),
    89: (
        ("NR", "Gate 1", True),
        ("PRE", "Micro Boost", True),
        ("WAH", "B-Wah", False),
        ("DST", "Bass Hammer", True),
        ("CAB/IR", "AMPG 8x10", True),
        ("EQ", "Bass EQ 1", True),
        ("MOD", "B-Jet", False),
        ("VOL", "Volume", True),
    ),
    90: (
        ("NR", "Gate 3", True),
        ("PRE", "COMP4", True),
        ("DST", "Black Bass", True),
        ("AMP", "Mess Bass", True),
        ("CAB/IR", "Mess BS 2x10", True),
        ("VOL", "Volume", True),
    ),
    91: (
        ("NR", "Gate 1", True),
        ("PRE", "COMP", True),
        ("WAH", "B-Wah", False),
        ("DST", "Lazaro", True),
        ("AMP", "Bass Pre", True),
        ("CAB/IR", "Tracy 4x10", True),
        ("EQ", "Bass EQ 1", True),
        ("VOL", "Volume", True),
    ),
    92: (
        ("PRE", "COMP4", True),
        ("AMP", "Classic Bass", True),
        ("CAB/IR", "AMPG 8x10", True),
        ("EQ", "Guitar EQ 2", True),
        ("MOD", "B-Chorus", True),
        ("RVB", "Spring", True),
        ("VOL", "Volume", True),
    ),
    93: (
        ("PRE", "T-Wah", True),
        ("AMP", "Classic Bass", True),
        ("CAB/IR", "MATT 2x12", True),
        ("EQ", "Guitar EQ 2", True),
        ("VOL", "Volume", True),
    ),
    94: (
        ("NR", "Gate 1", True),
        ("PRE", "COMP4", True),
        ("WAH", "B-Wah", False),
        ("DST", "Lazaro", True),
        ("AMP", "Bass Pre", True),
        ("CAB/IR", "AMPG 8x10", True),
        ("EQ", "Bass EQ 1", True),
        ("MOD", "Detune", True),
        ("RVB", "Room", True),
        ("VOL", "Volume", True),
    ),
    95: (
        ("NR", "Gate 3", False),
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", False),
        ("EQ", "Guitar EQ 2", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    96: (
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", False),
        ("EQ", "Guitar EQ 1", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    97: (
        ("PRE", "COMP", True),
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", False),
        ("EQ", "Guitar EQ 1", True),
        ("DLY", "Sweep Echo", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    98: (
        ("PRE", "Pitch", True),
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", False),
        ("EQ", "Guitar EQ 1", True),
        ("RVB", "Hall", True),
        ("VOL", "Volume", True),
    ),
    99: (
        ("NR", "Gate 3", True),
        ("AMP", "AC Pre", True),
        ("CAB/IR", "AC", False),
        ("EQ", "Guitar EQ 2", True),
        ("RVB", "Hall", True),
        ("PRE", "COMP4", True),
        ("VOL", "Volume", True),
    ),
    100: (
        ("NR", "Gate 1", True),
        ("PRE", "OD 9", True),
        ("AMP", "UK 45", True),
        ("CAB/IR", "UK Vintage 4x12", True),
        ("RVB", "Room", True),
        ("VOL", "Volume", True),
    ),
    102: (
        ("AMP", "Dark Twin", True),
        ("CAB/IR", "Twin 2x12", True),
        ("DLY", "Tape", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    103: (
        ("NR", "Gate 1", True),
        ("AMP", "UK 45JP", True),
        ("CAB/IR", "UK 2x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("DLY", "Tape", True),
        ("RVB", "Plate", True),
        ("VOL", "Volume", True),
    ),
    109: (
        ("NR", "Gate 1", True),
        ("PRE", "Boost", True),
        ("DST", "Micro Boost", False),
        ("AMP", "Dizz VH", True),
        ("CAB/IR", "Dizz 4x12", True),
        ("EQ", "Guitar EQ 1", True),
        ("MOD", "Freeze", False),
        ("DLY", "Digital Delay S", True),
        ("RVB", "Plate", False),
        ("VOL", "Volume", True),
    ),
}

PresetRow = tuple[int, str, str | None, str | None, tuple[str, ...], str]


PRESETS: tuple[PresetRow, ...] = (
    (1, "New GEN.", "modern", None, ("generic", "modern"), "Generic modern tone."),
    (2, "Dark Clean", "clean", None, ("dark",), "Dark clean preset."),
    (3, "Tweedy OD", "blues rock", None, ("fender", "tweed", "overdrive"), "Fender Tweed-style overdrive."),
    (4, "Foxy Clean", "british clean", None, ("vox", "ac30", "clean"), "Likely Vox AC-style clean."),
    (5, "Foxy OD", "british rock", None, ("vox", "ac30", "overdrive"), "Likely Vox AC-style overdrive."),
    (6, "UK900 DIST", "hard rock", None, ("marshall", "jcm900", "distortion"), "Marshall JCM900-style distortion."),
    (7, "Mess DIST", "metal", None, ("mesa", "rectifier", "distortion"), "Mesa/Boogie-style distortion."),
    (8, "Match Clean", "clean", None, ("matchless", "clean"), "Matchless-style clean."),
    (9, "Match OD", "rock", None, ("matchless", "overdrive"), "Matchless-style overdrive."),
    (10, "EV51 DIST", "hard rock", None, ("5150", "evh", "distortion"), "Likely EVH 5150-style distortion."),
    (11, "Morse Purple", "hard rock", "Steve Morse", ("deep purple",), "Likely Steve Morse / Deep Purple reference."),
    (12, "Gypsy of AT", "melodic rock", "Andy Timmons", ("electric gypsy",), "Likely Andy Timmons reference."),
    (13, "Love of Lord", "instrumental rock", "Steve Vai", ("for the love of god",), "Likely For the Love of God-style lead."),
    (14, "JS Iconic", "instrumental rock", "Joe Satriani", ("js",), "Likely Joe Satriani initials."),
    (15, "Neo-Classical", "neoclassical metal", "Yngwie Malmsteen", ("shred",), "Neoclassical lead style."),
    (16, "JP Iconic", "progressive metal", "John Petrucci", ("dream theater",), "Likely John Petrucci initials."),
    (17, "GG Iconic", "fusion", "Guthrie Govan", ("gg",), "Likely Guthrie Govan initials."),
    (18, "Racer of PG", "shred", "Paul Gilbert", ("racer x",), "Likely Paul Gilbert / Racer X reference."),
    (19, "MF Iconic", "melodic metal", "Marty Friedman", ("mf",), "Likely Marty Friedman initials; low confidence."),
    (20, "E.C. Iconic", "blues rock", "Eric Clapton", ("ec",), "Likely Eric Clapton initials."),
    (21, "Hendrix Riff", "psychedelic rock", "Jimi Hendrix", ("fuzz", "riff"), "Jimi Hendrix-style riff tone."),
    (22, "Red May", "classic rock", "Brian May", ("queen", "red special"), "Likely Brian May / Red Special reference."),
    (23, "Luke Iconic", "session rock", "Steve Lukather", ("toto",), "Likely Steve Lukather reference."),
    (24, "Mayer's OD", "blues pop", "John Mayer", ("overdrive",), "John Mayer-style overdrive."),
    (25, "Funky Clean", "funk", None, ("clean",), "Funk clean preset."),
    (26, "JAZZ Clean", "jazz", None, ("clean",), "Jazz clean preset."),
    (27, "Bluegrass", "bluegrass", None, ("acoustic",), "Bluegrass preset."),
    (28, "New wave CL", "new wave", None, ("clean", "chorus"), "New wave clean."),
    (29, "Thin Blues", "blues", None, ("thin",), "Thin blues tone."),
    (30, "Thick Blues", "blues", None, ("thick",), "Thick blues tone."),
    (31, "Fusion DST", "fusion", None, ("distortion",), "Fusion distortion."),
    (32, "Fusion OD", "fusion", None, ("overdrive",), "Fusion overdrive."),
    (33, "POP Lead", "pop", None, ("lead",), "Pop lead."),
    (34, "POP Rhythm", "pop", None, ("rhythm",), "Pop rhythm."),
    (35, "Chorus OD", "rock", None, ("chorus", "overdrive"), "Chorus overdrive."),
    (36, "Metal Core", "metalcore", None, ("metal",), "Metalcore preset."),
    (37, "Punk Rhythm", "punk", None, ("rhythm",), "Punk rhythm."),
    (38, "POP Punk", "pop punk", None, ("punk",), "Pop-punk preset."),
    (39, "J Rock", "j-rock", None, ("japanese rock",), "Japanese rock preset."),
    (40, "POST Clean", "post-rock", None, ("clean",), "Post-rock clean."),
    (41, "POST ROCK", "post-rock", None, ("ambient",), "Post-rock preset."),
    (42, "80s Clean", "80s pop", None, ("clean", "chorus"), "80s clean tone."),
    (43, "Purple Riff", "hard rock", "Deep Purple", ("smoke on the water",), "Likely Deep Purple riff reference."),
    (44, "Zeppelin Riff", "classic rock", "Led Zeppelin", ("jimmy page",), "Led Zeppelin-style riff tone."),
    (45, "Sabbath Riff", "doom metal", "Black Sabbath", ("tony iommi",), "Black Sabbath-style riff tone."),
    (46, "Back in DC", "hard rock", "AC/DC", ("back in black",), "AC/DC-style riff tone."),
    (47, "GNR Sound", "hard rock", "Guns N' Roses", ("slash",), "Guns N' Roses-style tone."),
    (48, "Numb of PF", "progressive rock", "Pink Floyd", ("comfortably numb", "david gilmour"), "Likely Pink Floyd / Comfortably Numb reference."),
    (49, "Motel CA", "classic rock", "Eagles", ("hotel california",), "Likely Hotel California reference."),
    (50, "Eddie Solo", "hard rock", "Eddie Van Halen", ("van halen", "solo"), "Eddie Van Halen-style solo tone."),
    (51, "Eddie Riff", "hard rock", "Van Halen", ("eddie van halen", "riff"), "Van Halen-style riff tone."),
    (52, "Bros in Dire", "classic rock", "Dire Straits", ("mark knopfler",), "Likely Dire Straits / Brothers in Arms reference."),
    (53, "Straits Clean", "classic rock", "Dire Straits", ("mark knopfler", "clean"), "Dire Straits-style clean tone."),
    (54, "Metal Maiden", "heavy metal", "Iron Maiden", ("maiden",), "Iron Maiden-style metal tone."),
    (55, "Metal of Lica", "thrash metal", "Metallica", ("metallica",), "Metallica-style metal tone."),
    (56, "Leopard DIST", "hard rock", "Def Leppard", ("def leppard",), "Likely Def Leppard reference."),
    (57, "Groove Cowboy", "groove metal", "Pantera", ("cowboys from hell",), "Likely Pantera / Cowboys from Hell reference."),
    (58, "Alexi & Child", "melodic death metal", "Children of Bodom", ("alexi laiho",), "Likely Alexi Laiho / Children of Bodom reference."),
    (59, "Psycho Knot", "nu metal", "Slipknot", ("psychosocial",), "Likely Slipknot reference."),
    (60, "Grunge of KC", "grunge", "Nirvana", ("kurt cobain",), "Likely Kurt Cobain initials."),
    (61, "Greenland", "pop punk", "Green Day", ("green day",), "Likely Green Day wordplay; low confidence."),
    (62, "Rammst. Metal", "industrial metal", "Rammstein", ("rammstein",), "Rammstein-style metal tone."),
    (63, "No More Doubt", "ska punk", "No Doubt", ("no doubt",), "No Doubt-style preset."),
    (64, "Really Love U", "pop rock", None, ("love",), "Song/artist inference unclear."),
    (65, "Ocean and Sky", "ambient", None, ("clean", "wide"), "Atmospheric clean preset."),
    (66, "Glorious Year", "pop rock", None, ("anthem",), "Song/artist inference unclear."),
    (67, "Hammony m3", "effect", None, ("harmony", "minor third"), "Harmony minor-third effect."),
    (68, "Hammony P5", "effect", None, ("harmony", "perfect fifth"), "Harmony perfect-fifth effect."),
    (69, "WAH-WAH LD", "effect", None, ("wah", "lead"), "Wah lead preset."),
    (70, "Auto Swell", "effect", None, ("swell",), "Auto-swell effect."),
    (71, "Step Filter", "effect", None, ("filter",), "Step filter effect."),
    (72, "Clean SYNC", "clean", None, ("sync",), "Synchronized clean effect preset."),
    (73, "Octave Fuzz", "fuzz", None, ("octave",), "Octave fuzz preset."),
    (74, "Ethereal RVB", "ambient", None, ("reverb",), "Ethereal reverb preset."),
    (75, "Leslie & Vibe", "effect", None, ("leslie", "vibe"), "Rotary/vibe preset."),
    (76, "Freeze", "effect", None, ("hold", "sustain"), "Freeze/hold effect."),
    (77, "Vibrato Jump", "effect", None, ("vibrato",), "Vibrato effect preset."),
    (78, "Crystal TREM", "effect", None, ("tremolo",), "Crystal tremolo preset."),
    (79, "Organ Synth", "synth", None, ("organ",), "Organ synth preset."),
    (80, "Luminous", "ambient", None, ("shimmer",), "Luminous ambient preset."),
    (81, "Pick-up S-H", "utility", None, ("single coil", "humbucker"), "Single-coil to humbucker pickup simulation."),
    (82, "Pick-up H-S", "utility", None, ("humbucker", "single coil"), "Humbucker to single-coil pickup simulation."),
    (83, "AC SIM", "acoustic", None, ("acoustic simulator",), "Acoustic simulator."),
    (84, "Hammy Pedal", "effect", None, ("whammy", "pitch"), "Whammy-style pitch pedal."),
    (85, "Tone crasher", "effect", None, ("bitcrusher", "tone"), "Tone/bit-crusher style effect."),
    (86, "Finger Bass", "bass", None, ("fingerstyle",), "Fingerstyle bass preset."),
    (87, "Pick Bass", "bass", None, ("pick",), "Picked bass preset."),
    (88, "Slap Bass", "bass", None, ("slap",), "Slap bass preset."),
    (89, "Bass Tapping", "bass", None, ("tapping",), "Bass tapping preset."),
    (90, "Bass Drive", "bass", None, ("drive",), "Bass drive preset."),
    (91, "Bass Dist", "bass", None, ("distortion",), "Bass distortion preset."),
    (92, "Bass Fuzz", "bass", None, ("fuzz",), "Bass fuzz preset."),
    (93, "Bass Chorus", "bass", None, ("chorus",), "Bass chorus preset."),
    (94, "Bass Q", "bass", None, ("filter", "q"), "Bass filter/Q preset."),
    (95, "Bass Synth", "bass synth", None, ("synth",), "Bass synth preset."),
    (96, "Bird AC", "acoustic", "The Beatles", ("blackbird",), "Likely Blackbird acoustic reference; low confidence."),
    (97, "Standard AC", "acoustic", None, ("standard",), "Standard acoustic preset."),
    (98, "Solo AC", "acoustic", None, ("solo",), "Acoustic solo preset."),
    (99, "12-Strings", "acoustic", None, ("12-string",), "12-string acoustic preset."),
    (100, "Finger AC", "acoustic", None, ("fingerstyle",), "Fingerstyle acoustic preset."),
    (101, "EC Cream", "blues rock", "Cream", ("eric clapton",), "Likely Eric Clapton / Cream reference."),
    (102, "It's GP-180", "demo", None, ("factory demo",), "Factory GP-180 showcase preset."),
    (103, "JohnMayer", "blues pop", "John Mayer", ("john mayer",), "John Mayer-style preset."),
    (104, "david bowie", "art rock", "David Bowie", ("david bowie",), "David Bowie-style preset."),
    (110, "MUSE", "alternative rock", "Muse", ("muse",), "Muse-style high-gain effect preset."),
)


BINDINGS: tuple[tuple[str, str, str], ...] = (
    ("genre", "bluegrass", "gp180-027-bluegrass"),
    ("genre", "blues", "gp180-030-thick-blues"),
    ("genre", "funk", "gp180-025-funky-clean"),
    ("genre", "jazz", "gp180-026-jazz-clean"),
    ("genre", "metalcore", "gp180-036-metal-core"),
    ("genre", "post-rock", "gp180-041-post-rock"),
    ("genre", "punk", "gp180-037-punk-rhythm"),
    ("genre", "pop punk", "gp180-038-pop-punk"),
    ("genre", "acoustic", "gp180-097-standard-ac"),
    ("genre", "bass", "gp180-086-finger-bass"),
    ("artist", "AC/DC", "gp180-046-back-in-dc"),
    ("artist", "Pink Floyd", "gp180-048-numb-of-pf"),
    ("artist", "Dire Straits", "gp180-053-straits-clean"),
    ("artist", "Metallica", "gp180-055-metal-of-lica"),
    ("artist", "Iron Maiden", "gp180-054-metal-maiden"),
    ("artist", "Black Sabbath", "gp180-045-sabbath-riff"),
    ("artist", "Led Zeppelin", "gp180-044-zeppelin-riff"),
    ("artist", "Van Halen", "gp180-051-eddie-riff"),
    ("artist", "Eddie Van Halen", "gp180-050-eddie-solo"),
    ("artist", "Guns N' Roses", "gp180-047-gnr-sound"),
    ("artist", "John Mayer", "gp180-103-johnmayer"),
    ("artist", "Eric Clapton", "gp180-020-e-c-iconic"),
    ("artist", "Cream", "gp180-101-ec-cream"),
    ("artist", "Jimi Hendrix", "gp180-021-hendrix-riff"),
    ("artist", "Brian May", "gp180-022-red-may"),
    ("artist", "Queen", "gp180-022-red-may"),
    ("artist", "David Bowie", "gp180-104-david-bowie"),
    ("song", "Back In Black", "gp180-046-back-in-dc"),
    ("song", "Comfortably Numb", "gp180-048-numb-of-pf"),
    ("song", "Hotel California", "gp180-049-motel-ca"),
    ("song", "Sultans Of Swing", "gp180-053-straits-clean"),
    ("song", "Brothers In Arms", "gp180-052-bros-in-dire"),
    ("song", "Whole Lotta Love", "gp180-044-zeppelin-riff"),
    ("song", "Paranoid", "gp180-045-sabbath-riff"),
    ("song", "Enter Sandman", "gp180-055-metal-of-lica"),
    ("song", "Sweet Child O' Mine", "gp180-047-gnr-sound"),
    ("song", "Eruption", "gp180-050-eddie-solo"),
    ("song", "For The Love Of God", "gp180-013-love-of-lord"),
    ("song", "Smoke On The Water", "gp180-043-purple-riff"),
    ("song", "Smells Like Teen Spirit", "gp180-060-grunge-of-kc"),
)


def _profile_id(slot: int, name: str) -> str:
    slug = name.lower().replace("&", "and")
    slug = re.sub(r"[^a-z0-9]+", "-", slug).strip("-")
    return f"gp180-{slot:03d}-{slug}"


def build_bank() -> RigBank:
    profiles = []
    for slot, name, genre, artist, tags, inference in PRESETS:
        profile_tags = ("factory", f"slot-{slot:03d}", *tags)
        notes = f"Captured GP-180 preset name. Inference: {inference}"
        profiles.append(
            RigProfile(
                id=_profile_id(slot, name),
                name=f"{slot:03d} {name}",
                program=slot - 1,
                artist=artist,
                genre=genre,
                tags=profile_tags,
                source=SOURCE,
                notes=notes,
            )
        )
    bindings = tuple(
        RigBinding(scope=scope, key=key, profile_id=profile_id)
        for scope, key, profile_id in BINDINGS
    )
    return RigBank(profiles=tuple(profiles), bindings=bindings)


def _apply_captured_modules(output: Path) -> None:
    """Preserve verified module chains when regenerating ignored bank JSON."""

    document = json.loads(output.read_text(encoding="utf-8"))
    profiles = document.get("profiles") if isinstance(document, dict) else None
    if not isinstance(profiles, list):
        raise ValueError("generated rig bank has no profiles list")
    for profile in profiles:
        if not isinstance(profile, dict):
            continue
        module_rows = CAPTURED_MODULES.get(profile.get("program"))
        if module_rows is None:
            continue
        profile["modules"] = [
            {"module": module, "model": model, "active": active}
            for module, model, active in module_rows
        ]
        profile["source"] = MODULE_SOURCE
        notes = str(profile.get("notes") or "")
        profile["notes"] = notes.replace(
            "Captured GP-180 preset name.",
            "Captured preset name and active chain from user screenshot.",
        )
    output.write_text(
        json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output",
        nargs="?",
        default="partitions/rigs/rig_bank.json",
        help="Destination rig_bank.json path.",
    )
    args = parser.parse_args()
    output = Path(args.output)
    bank = build_bank()
    save_rig_bank(output, bank)
    _apply_captured_modules(output)
    print(f"Wrote {len(bank.profiles)} profiles and {len(bank.bindings)} bindings to {output}")


if __name__ == "__main__":
    main()
